In [13]:
import numpy as np
import pandas as pd
%matplotlib inline 
import re
from datetime import datetime
from datetime import timedelta

pd.options.display.max_columns = 100

In [4]:
df = pd.read_csv('report-1524135937.csv')

In [10]:
df.head()

,id,sex,ref,age,country,p.0.0,p.0.1,p.0.2,p.0.3,p.0.4,p.0.5,p.0.6,p.0.7,p.1.0,p.1.1,p.1.2,p.1.3,p.1.4,p.1.5,p.1.6,p.1.7,p.2.0,p.2.1,p.2.2,p.2.3,p.3.4,p.3.5,p.3.6,p.3.7,s.0.1,s.0.2,s.0.3,s.0.5,s.0.6,s.0.7,s.0.9,s.0.10,s.0.11,s.0.12,s.0.13,s.0.8,s.0.4,s.1.1,s.1.2,s.1.3,s.1.5,s.1.6,s.1.7,s.1.9,s.1.10,s.1.11,s.1.12,s.1.13,s.1.8,s.1.4,s.2.2,s.2.3,s.2.6,s.2.7,s.3.8,s.3.4,s.3.10,s.3.11
0,104755994,1,NaN,26.0,Россия,2.70,16.22,38.10,19.05,8.59,1.84,111.11,90.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.33,3.33,26.67,13.33,50,30,30,90,37,1,6,21,8,4,163,14,3,9,10,10,9,4,0,0,1,0,0,0,0,0,0,0,0,0,1,1,8,4,3,9,5,3
1,91382514,0,NaN,39.0,Украина,0.66,3.21,59.19,3.93,21.32,6.99,75.94,131.67,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.67,0.00,100.00,13.33,100,100,60,60,18266,120,586,789,467,31,1787,381,125,5213,3959,3959,5213,370,0,0,202,0,0,0,0,0,1,0,0,1,20,0,30,4,6,6,10,10
2,35095882,1,NaN,35.0,Россия,2.36,18.75,5.90,34.00,3.83,6.80,57.89,172.73,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.67,0.00,0.00,96.67,0,60,80,80,4368,103,819,1203,71,409,1882,72,128,266,154,154,266,1,0,0,26,0,0,0,0,0,0,0,0,0,29,0,0,29,8,8,0,6
3,105658364,1,1.0,60.0,Индия,0.31,2.16,50.00,0.00,3.45,7.76,50.00,200.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.33,0.00,3.33,0.00,0,90,20,40,324,1,7,2,1,0,116,4,9,4,2,2,4,210,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,2,4,0,9
4,115007806,1,1.0,39.0,Бангладеш,2.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.33,0.00,0.00,0.00,0,0,0,0,43,1,0,1,0,0,10,0,0,0,0,0,0,36,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

`p.x.y`
p - Проценты 
x - Тип 0-3 
0 - Все время
1 - Ссесия
2 - Последние 30 симпатии
3 - Последние 10 сообщения

y - Метрики 0-7
0 - Процент положительного ответа на исходящие симпатии от пользователя (% ответа ему)
1 - Процент положительного ответа на симпатии
2 - Процент положительного ответа на исходящие взаимные симпатии от пользователя (% ответа ему)
3 - Процент положительного ответа на взаимные симпатии
4 - Процент ответа на первые сообщения
5 - Процент ответа на его первые сообщения
6 - Процент ответов на непервые сообщения
7 - Процент ответов на его непервые сообщения

`s.x.y`
s - Счетчики по которым считаются метрики.
x - Тип 0-3 
0 - Все время
1 - Ссесия
2 - Последние 30 симпатии
3 - Последние 10 сообщения

y - Счетчики 1-13
1 - Счетчик входящей активности, связанной с лайками
2 - Счетчики положительных ответов на исходящую симпатию
3 - Счетчики положительных ответов на входящую симпатию
4 - Счетчики ответов в процессе диалога, сколько ответил
5 - Счетчики отправленных и полученных взаимных симпатий
6 - Счетчики положительных ответов на исходящую взаимную симпатию
7 - Счетчики положительных ответов на входящую взаимную симпатию
8 - Счетчики ответов в процессе диалога, сколько ответили ему
9 - Счетчики первого контакта
10 - Счетчики ответов на первый контакт, сколько ответил
11 - Счетчики ответов на первый контакт, сколько ответили ему
12 - Счетчики ответов в процессе диалога, сколько ответил
13 - Счетчики ответов в процессе диалога, сколько ответили ему

Метрики считаются так: 2ключ * 100 /1ключ
0 - Процент положительного ответа на исходящие симпатии от пользователя (% ответа ему)
>1 - Счетчик входящей активности, связанной с лайками
>2 - Счетчики положительных ответов на исходящую симпатию

1 - Процент положительного ответа на симпатии
>1 - Счетчик входящей активности, связанной с лайками
>3 - Счетчики положительных ответов на входящую симпатию

2 - Процент положительного ответа на исходящие взаимные симпатии от пользователя (% ответа ему)
>5 - Счетчики отправленных и полученных взаимных симпатий
>6 - Счетчики положительных ответов на исходящую взаимную симпатию

3 - Процент положительного ответа на взаимные симпатии
>5 - Счетчики отправленных и полученных взаимных симпатий
>7 - Счетчики положительных ответов на входящую взаимную симпатию

4 - Процент ответа на первые сообщения
>9 - Счетчики первого контакта
>10 - Счетчики ответов на первый контакт, сколько ответил

5 - Процент ответа на его первые сообщения
>9 - Счетчики первого контакта
>11 - Счетчики ответов на первый контакт, сколько ответили ему

6 - Процент ответов на непервые сообщения
>12 - Счетчики ответов в процессе диалога, сколько ответил
>8 - Счетчики ответов в процессе диалога, сколько ответили ему

7 - Процент ответов на его непервые сообщения
>13 - Счетчики ответов в процессе диалога, сколько ответили ему
>4 - Счетчики ответов в процессе диалога, сколько ответил

In [12]:
df.describe()

,id,sex,ref,age,p.0.0,p.0.1,p.0.2,p.0.3,p.0.4,p.0.5,p.0.6,p.0.7,p.1.0,p.1.1,p.1.2,p.1.3,p.1.4,p.1.5,p.1.6,p.1.7,p.2.0,p.2.1,p.2.2,p.2.3,p.3.4,p.3.5,p.3.6,p.3.7,s.0.1,s.0.2,s.0.3,s.0.5,s.0.6,s.0.7,s.0.9,s.0.10,s.0.11,s.0.12,s.0.13,s.0.8,s.0.4,s.1.1,s.1.2,s.1.3,s.1.5,s.1.6,s.1.7,s.1.9,s.1.10,s.1.11,s.1.12,s.1.13,s.1.8,s.1.4,s.2.2,s.2.3,s.2.6,s.2.7,s.3.8,s.3.4,s.3.10,s.3.11
count,8.547400e+04,85474.000000,8523.0,85471.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.00000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,8.547400e+04,85474.000000,8.547400e+04,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.00000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000,85474.000000
mean,8.780497e+07,0.746356,1.0,36.960548,16.752545,13.290123,27.460978,60.690749,11.396046,11.033970,210.797316,239.224950,0.607448,1.053231,0.499724,3.113898,0.009314,0.000061,9.188709,3.651585,50.760511,8.909180,27.362622,43.12864,23.803145,47.008915,52.038632,33.989751,3352.609905,587.525119,376.416922,1.675768e+03,628.629525,6.402915e+02,1128.787959,127.028547,182.135445,1492.122540,2243.802946,2264.442778,1471.482708,660.337050,0.080761,2.559679,94.318553,0.052414,0.113754,4.383228,4.837565,0.09583,2.617439,0.758371,0.758371,2.617439,15.228140,2.672789,8.208812,12.938590,5.203863,3.398975,2.380314,4.700891
std,3.338974e+07,0.435099,0.0,14.433302,24.625698,24.874929,27.459640,321.730101,94.105409,95.570733,1330.679357,3073.494531,5.934485,8.847898,5.529777,27.364496,1.278193,0.012581,107.792755,29.945122,44.188403,18.827242,32.353785,42.11687,34.743842,44.877882,43.454763,37.979521,11128.571140,3343.571121,1870.480622,7.615029e+03,2318.529067,1.653081e+04,3117.643121,986.002818,806.776617,5631.104387,8453.620752,8523.140683,5564.356243,4275.877248,0.682497,297.707598,896.058353,0.533123,1.043029,556.306835,576.995452,7.80721,301.492480,52.985640,52.985640,301.492480,13.256439,5.648158,9.706097,12.635002,4.345476,3.797952,3.474384,4.487788
min,1.000000e+00,0.000000,1.0,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.401103e+07,0.000000,1.0,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,116.000000,0.000000,0.000000,1.000000e+00,0.000000,0.000000e+00,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.028884e+08,1.000000,1.0,33.000000,2.960000,5.530000,21.990000,14.640000,2.310000,2.630000,75.165000,37.575000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,13.330000,26.67000,10.000000,30.000000,60.000000,20.000000,403.000000,18.000000,28.000000,6.100000e+01,16.000000,1.700000e+01,185.000000,7.000000,7.000000,63.000000,74.000000,75.000000,62.000000,43.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,15.000000,0.000000,4.000000,8.000000,6.000000,2.000000,1.000000,3.000000
75%,1.148025e+08,1.000000,1.0,45.000000,25.490000,17.370000,47.000000,43.480000,9.240000,11.140000,203.920000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,6.670000,50.000000,93.33000,30.000000,100.000000,100.000000,70.000000,1943.000000,192.000000,216.000000,8.510000e+02,290.000000,2.080000e+02,977.000000,51.000000,75.000000,719.000000,1022.000000,1031.000000,711.000000,192.000000,0.000000,0.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,30.000000,2.000000,15.000000,28.000000,10.000000,7.000000,3.000000,10.000000
max,1.180202e+08,1.000000,1.0,99.000000,100.000000,2800.000000,300.000000,23400.000000,13300.000000,13700.000000,287300.000000,403883.330000,100.000000,500.000000,100.000000,2900.000000,300.760000,2.770000,11100.000000,2500.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,384684.000000,231696.000000,142760.000000,1.284225e+06,79153.000000,4.686930e+06,119232.000000,149229.000000,73901.000000,366803.000000,323056.000000,329894.000000,366803.000000,366785.000000,50.000000,47993.000000,73763.000000,36.000000,70.000000,86580.000000,87925.000000,2238.00000,50387.000000,14276.000000,14276.000000,50387.000000,30.000000,30.000000,30.000000,30.000000,10.000000,10.000000,10.000000,10.000000

In [26]:
# symp, mut, first_dial, rep_dial
df[df['sex'] == 0][['p.2.1','p.2.3','p.3.4','p.3.6']].describe()

              p.2.1         p.2.3         p.3.4         p.3.6
count  21680.000000  21680.000000  21680.000000  21680.000000
mean       0.435693     33.253041     40.181273     43.770295
std        3.580939     38.099765     43.018188     40.242253
min        0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000
50%        0.000000     13.330000     20.000000     40.000000
75%        0.000000     70.000000    100.000000     90.000000
max      100.000000    100.000000    100.000000    100.000000

In [27]:
# symp, mut, first_dial, rep_dial
df[df['sex'] == 1][['p.2.1','p.2.3','p.3.4','p.3.6']].describe()

              p.2.1         p.2.3         p.3.4         p.3.6
count  63794.000000  63794.000000  63794.000000  63794.000000
mean      11.788843     46.484801     18.237138     54.848575
std       20.925540     42.883067     29.433846     44.142834
min        0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000
50%        0.000000     36.670000      0.000000     70.000000
75%       13.330000     96.670000     20.000000    100.000000
max      100.000000    100.000000    100.000000    100.000000

In [31]:
[df[(df['sex'] == 0) & (df['p.2.1'] > 0)].shape[0] / df[(df['sex'] == 0)].shape[0],
 df[(df['sex'] == 0) & (df['p.2.3'] > 0)].shape[0] / df[(df['sex'] == 0)].shape[0],
 df[(df['sex'] == 0) & (df['p.3.4'] > 0)].shape[0] / df[(df['sex'] == 0)].shape[0],
 df[(df['sex'] == 0) & (df['p.3.6'] > 0)].shape[0] / df[(df['sex'] == 0)].shape[0]]

[0.037407749077490775,
 0.611439114391144,
 0.6288284132841329,
 0.6752767527675276]

In [32]:
[df[(df['sex'] == 1) & (df['p.2.1'] > 0)].shape[0] / df[(df['sex'] == 1)].shape[0],
 df[(df['sex'] == 1) & (df['p.2.3'] > 0)].shape[0] / df[(df['sex'] == 1)].shape[0],
 df[(df['sex'] == 1) & (df['p.3.4'] > 0)].shape[0] / df[(df['sex'] == 1)].shape[0],
 df[(df['sex'] == 1) & (df['p.3.6'] > 0)].shape[0] / df[(df['sex'] == 1)].shape[0]]

[0.4494936827914851,
 0.722262281719284,
 0.46902530018497035,
 0.6910367746183027]

In [38]:
df[(df['sex'] == 0)]['p.2.1'].describe()

count    21680.000000
mean         0.435693
std          3.580939
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        100.000000
Name: p.2.1, dtype: float64

In [39]:
df[(df['sex'] == 0) & (df['p.2.1'] > 0)].shape[0] / df[(df['sex'] == 0)].shape[0]

0.037407749077490775

In [45]:
df[(df['sex'] == 0) & (df['s.2.3'] > 0)].shape[0] / df[(df['sex'] == 0)].shape[0]

0.037407749077490775

0.037407749077490775

In [46]:
df[(df['sex'] == 1) & (df['p.2.1'] > 0)].shape[0] / df[(df['sex'] == 1)].shape[0]

0.4494936827914851

In [47]:
df[(df['sex'] == 1) & (df['s.2.3'] > 0)].shape[0] / df[(df['sex'] == 1)].shape[0]

0.4494936827914851